In [1]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Input training and testing datasets from Kaggle, already split:
train=pd.read_csv(r"C:\Users\giant\OneDrive\Documents\_GCU_\mnist_train.csv")
test=pd.read_csv(r"C:\Users\giant\OneDrive\Documents\_GCU_\mnist_test.csv")

In [6]:
train.shape

(60000, 785)

In [7]:
test.shape

(10000, 785)

In [9]:
# There are 748 input variables and one output vector. Each input corresponds to a pixel
# in a 28x28 image. (Thus, 28^2=748 variables)
# For example, below "1x1" is the top left pixel, "1x2" is the one next to it, etc.
# The output variable is simply the label, a handwritten single digit arabic numeral. 
train.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
# This data is used as an example for this assignment to showcase the k-nearest neighbors
# classification algorithm. This is a method that makes no assumptions about the relationship
# between the regressor (digit, or label in the above table) and its predictors. 
# This algorithm uses distance measure to calculate the (Euclidean) distance a certain record is away from each
# of its k neighbors. Class conditional density estimates are used to approximate the actual probability
# density function that the sample is being drawn from. 
# The end result is very similar to that of the Naive Bayes classifier; probability functions
# are calculated using the distance to each neighbor, which results in "votes" being cast equally
# from each neighbor on which class the sample belongs to. 

In [92]:
import math
# To give an example of how the kNN algorithm works, 
# we take a random pair of images and will find the 
# Euclidean distance between them
def euc_dist(i,j):
    return math.sqrt(sum((i-j)**2))
i1=train.iloc[7]
i2=test.iloc[7]
euc_dist(i1,i2)

2727.785365456747

In [3]:
Xtrain=train.iloc[:,1:785]
ytrain=train['label']
Xtest=test.iloc[:,1:785]
ytest=test['label']

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
knn1 = KNeighborsClassifier(n_neighbors=5)
kmod = knn1.fit(Xtrain,ytrain)
ypred = kmod.predict(Xtest)
print("Accuracy:",metrics.accuracy_score(ytest, ypred))

Accuracy: 0.9688


In [46]:
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
# Now we implement the confusion matrix for all ten digits.
# We note that the vast majority of values are in the diagonal, 
# as suggested by the accuracy figure above.
pd.crosstab(ytest, ypred, rownames = ['Actual'], colnames =['Predicted'], margins = True)

Predicted     0     1     2     3    4    5    6     7    8     9    All
Actual                                                                  
0           974     1     1     0    0    1    2     1    0     0    980
1             0  1133     2     0    0    0    0     0    0     0   1135
2            11     8   991     2    1    0    1    15    3     0   1032
3             0     3     3   976    1   13    1     6    3     4   1010
4             3     7     0     0  944    0    4     2    1    21    982
5             5     0     0    12    2  862    4     1    2     4    892
6             5     3     0     0    3    2  945     0    0     0    958
7             0    22     4     0    3    0    0   988    0    11   1028
8             8     3     5    13    6   12    5     5  913     4    974
9             5     7     3     9    7    3    1    10    2   962   1009
All        1011  1187  1009  1012  967  893  963  1028  924  1006  10000

In [47]:
print(classification_report(ytest, ypred))
# The overall precision and recall are similarly very high, and differ only slightly by digit. 
# Note the perfect recall for 1's as well

              precision    recall  f1-score   support

           0       0.96      0.99      0.98       980
           1       0.95      1.00      0.98      1135
           2       0.98      0.96      0.97      1032
           3       0.96      0.97      0.97      1010
           4       0.98      0.96      0.97       982
           5       0.97      0.97      0.97       892
           6       0.98      0.99      0.98       958
           7       0.96      0.96      0.96      1028
           8       0.99      0.94      0.96       974
           9       0.96      0.95      0.95      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000



In [50]:
# As suggested above, the high precision, recall and accuracy figures suggest a good fit for this model. 
# If we remember that the integral representing the area under this curve
# gives us a more comprehensive metric, a good fit for this figure
# should be represented by a curve that hugs the top and left sides of the square

In [96]:
# Our test element is the seventh record, which is a number 9
i2[0]

9

In [93]:
# Our test element is reshaped to fit the function, then the predict()
# method is called to show the model correctly classified it as a 9
i2=(np.array(i2)).reshape(1,-1)
i2=np.delete(i2,0,axis=1)
kmod.predict(i2)

array([9], dtype=int64)

In [94]:
# The distance between the test element and each of its k nearest neighbors,
# along with indicies for the nearest points in the popualtion matrix
kmod.kneighbors(i2)

(array([[1289.69880205, 1396.00250716, 1407.50630549, 1458.50951317,
         1470.16529683]]),
 array([[41982, 56597, 25446, 14815, 48818]], dtype=int64))

In [99]:
#Probability estimates for the test element, shown to be certain that it is a 9
kmod.predict_proba(i2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [101]:
# The total error, or simply 1-Accuracy
round(1-metrics.accuracy_score(ytest, ypred),4)

0.0312